### PR TITLE
Sed 1074 monitoring table

### PR DESCRIPTION
**Pull request by dvladir**

### CODE REVIEW

**Review by neogucky — APPROVED** [review]
Now everything makes sense to me!

**Comment by chillbirdo** [comment]
Status filter fails on multiple selection:
image
image

**Comment by chillbirdo** [comment]
:wastebasket:  Delete button is missing

**Comment by chillbirdo** [comment]
Did you try to execute? I get an error, which I do not get in the old version for the same Plan
image

**Review by chillbirdo — CHANGES_REQUESTED** [review]
code looks good, but some functionality missing, see comments above

**Comment by dvladir** [comment]
@chillbirdo I've fix two other issues. Please, check the PR in bitbucket

**Comment by chillbirdo** [comment]
Sry about the Delete Button, I mixed with Scheduler view

**Review by chillbirdo — APPROVED** [review]

**Pull request merged**
