### PR TITLE
Sed 1074 refactor monitoring table

### PR DESCRIPTION
**Pull request by dvladir**

### CODE REVIEW

**Comment by neogucky** [comment]
Note: We need to merge this branch and also step-ee branch

**Comment by neogucky** [comment]
@neogucky Remember to merge SED-987 first.

**Comment by neogucky** [comment]
@dvladir There seems to be a lot of content regarding timeseries in this PR, is this required for the monitoring dashboard?

**Comment by dvladir** [comment]
> @dvladir There seems to be a lot of content regarding timeseries in this PR, is this required for the monitoring dashboard?

@neogucky Probably not. @lucianbaciu can you give more details about it?
If timerseries changes are not required, changes for monitoring table should be placed in another branch, and PR should be recreated.

**Pull request closed without merging**
